### ISSUE TITLE
TypeError in IG_Unpinner. IG ARM ver 27.0.0.7.97

### ISSUE THREAD

**Issue by GHXST01** [EquiFox/Instagram-Unpinner#2]
```
Traceback (most recent call last):
  File ".\IG_Unpinner.py", line 311, in <module>
    main()
  File ".\IG_Unpinner.py", line 295, in main
    if apply_patches():
  File ".\IG_Unpinner.py", line 252, in apply_patches
    if native_ssl_verify_patch(work_dir):
  File ".\IG_Unpinner.py", line 209, in native_ssl_verify_patch
    return arm32_ssl_verify_patch(project_folder)
  File ".\IG_Unpinner.py", line 176, in arm32_ssl_verify_patch
    method_offset = hex_string.find("c0f8c8100ab1c0f8cc207047")
TypeError: a bytes-like object is required, not 'str'
```

**Comment by GHXST01** [comment]
I'm guessing the script is written based on python 2.7 where strings are byte objects.
For anyone running 3.x, make the strings explicit byte objects by using the b"string" syntax.
